'use strict';
// Checking GitHub for a newer build, and installing it over this one.
//
// Deliberately not electron-updater: that needs a latest.yml generated by an automated publish,
// and this project's installers are attached to releases by hand. So the check reads the plain
// Releases API and the install runs the release's own NSIS installer, which upgrades in place
// and leaves %APPDATA% alone — settings, per-game records and the games themselves survive.
//
// Safety rules, because this downloads and runs an executable:
//   * only ever from the one pinned repository, over https, on github.com
//   * only an .exe asset whose name matches the product, never an arbitrary link
//   * the finished file must start with MZ and match the size the API advertised
//   * nothing is downloaded or run without the user pressing the button
const fs = require('fs');
const os = require('os');
const path = require('path');
const https = require('https');
const { spawn } = require('child_process');

const REPO = 'Aryansingh0783/refract';
const API = `https://api.github.com/repos/${REPO}/releases/latest`;
const RELEASES_PAGE = `https://github.com/${REPO}/releases/latest`;
// Where an asset is allowed to come from. Anything else is refused, whatever the API says.
const ASSET_HOST = /^https:\/\/(github\.com|objects\.githubusercontent\.com|release-assets\.githubusercontent\.com)\//;
const INSTALLER_RE = /^(DIHLSS5|Refract)-Setup-[\d.]+(-lite)?\.exe$/i;

// "0.5.0" vs "v0.5.1" -> -1 / 0 / 1, ignoring anything after the numbers.
function compare(a, b) {
  const nums = v => String(v || '').replace(/^v/i, '').split(/[^\d]+/).filter(x => x !== '').map(Number);
  const x = nums(a), y = nums(b);
  for (let i = 0; i < Math.max(x.length, y.length); i++) {
    const d = (x[i] || 0) - (y[i] || 0);
    if (d) return d < 0 ? -1 : 1;
  }
  return 0;
}

function getJson(url, { get = httpsGet } = {}) {
  return get(url, { Accept: 'application/vnd.github+json' }).then(b => JSON.parse(b.toString('utf8')));
}

function httpsGet(url, headers = {}, redirects = 5) {
  return new Promise((resolve, reject) => {
    const req = https.get(url, { headers: { 'User-Agent': 'DIHLSS5-updater', ...headers } }, res => {
      if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
        res.resume();
        if (!redirects) return reject(new Error('Too many redirects.'));
        return resolve(httpsGet(new URL(res.headers.location, url).toString(), headers, redirects - 1));
      }
      if (res.statusCode !== 200) { res.resume(); return reject(new Error(`GitHub replied ${res.statusCode}.`)); }
      const chunks = [];
      res.on('data', c => chunks.push(c));
      res.on('end', () => resolve(Buffer.concat(chunks)));
    });
    req.on('error', reject);
    req.setTimeout(20000, () => req.destroy(new Error('Timed out reaching GitHub.')));
  });
}

// Pick the installer from a release's assets: the full build first, a lite build only if that is
// all there is. Returns null when the release has no installer attached (which happens when one
// is published before the file is uploaded).
function pickAsset(assets = []) {
  const usable = assets.filter(a => INSTALLER_RE.test(a.name || '') && ASSET_HOST.test(a.browser_download_url || ''));
  if (!usable.length) return null;
  return usable.find(a => !/-lite\.exe$/i.test(a.name)) || usable[0];
}

// What the newest release is, and whether it is newer than this build.
async function check(current, { fetchJson = getJson } = {}) {
  const rel = await fetchJson(API);
  if (!rel || !rel.tag_name) throw new Error('GitHub did not return a release.');
  const latest = String(rel.tag_name).replace(/^v/i, '');
  const asset = pickAsset(rel.assets);
  return {
    current, latest,
    newer: compare(current, latest) < 0,
    name: rel.name || rel.tag_name,
    notes: rel.body || '',
    page: rel.html_url || RELEASES_PAGE,
    asset: asset ? { name: asset.name, url: asset.browser_download_url, size: asset.size } : null,
    // A newer release with nothing attached can only be handled by sending the user to the page.
    downloadable: !!asset,
  };
}

// Fetch the installer to a temp file, checking as we go. Returns its path.
async function download(asset, { dir = os.tmpdir(), onProgress = null, get = httpsGet } = {}) {
  if (!asset || !ASSET_HOST.test(asset.url || '')) throw new Error('That download does not come from the project\'s own GitHub releases.');
  if (!INSTALLER_RE.test(asset.name || '')) throw new Error('That release asset is not a DIHLSS5 installer.');
  const out = path.join(dir, asset.name);
  const buf = await get(asset.url, {}, 5, onProgress);
  if (asset.size && buf.length !== asset.size) {
    throw new Error(`The download is ${buf.length} bytes, but GitHub said ${asset.size}. Not running it.`);
  }
  if (buf.length < 1 << 20 || buf[0] !== 0x4d || buf[1] !== 0x5a) {
    throw new Error('The download is not a Windows installer. Not running it.');
  }
  await fs.promises.writeFile(out, buf);
  return out;
}

// Run the downloaded installer and let it replace this install. NSIS upgrades in place and does
// not touch %APPDATA%, so settings and every game record survive. The app must quit right after,
// because the installer cannot replace files this process has open.
function install(file, { spawnFn = spawn } = {}) {
  if (!file || !/\.exe$/i.test(file) || !fs.existsSync(file)) throw new Error('The installer is not where it should be.');
  const child = spawnFn(file, [], { detached: true, stdio: 'ignore' });
  child.unref();
  return true;
}

module.exports = { check, download, install, compare, pickAsset, REPO, RELEASES_PAGE, API, INSTALLER_RE, ASSET_HOST };
